#! /bin/bash

cd `dirname $0`

arch="`uname -m`"
tag=
platform=
while test "$#" -ne 0; do
    if test "$1" = "-a" -o "$1" = "--arm" -o "$1" = "--arm64"; then
        if test "`arch`" = "arm64" -o "`arch`" = "aarch64"; then
            platform=linux/arm64
            shift
        else
            echo "\`cs300-build-docker --arm\` only works on ARM64 hosts" 1>&2
            exit 1
        fi
    elif test "$1" = "-x" -o "$1" = "--x86-64" -o "$1" = "--x86_64" -o "$1" = "--amd64"; then
        platform=linux/amd64
    else
        armtext=
        if test "`arch`" = "arm64" -o "`arch`" = "aarch64"; then
            armtext=" [-a|--arm] [-x|--x86-64]"
        fi
        echo "Usage: cs300-build-docker$armtext" 1>&2
        exit 1
    fi
done
if test -z "$platform" -a \( "$arch" = "arm64" -o "$arch" = "aarch64" \); then
    platform=linux/arm64
elif test -z "$platform"; then
    platform=linux/amd64
fi
if test -z "$tag" -a "$platform" = linux/arm64; then
    tag=cs300:arm64
elif test -z "$tag"; then
    tag=cs300:latest
fi

container_exec=docker
container_file=Dockerfile
if command -v 'podman' &> /dev/null; then
	echo "podman found - using to build container"
	container_exec=podman
	container_file=Podmanfile
	podman system migrate
fi

if test $platform = linux/arm64; then
    exec $container_exec build -t "$tag" -f $container_file.arm64 --platform linux/arm64 --build-arg USER=$USER .
else
    exec $container_exec build -t "$tag" -f $container_file --platform linux/amd64 --build-arg USER=$USER .
fi
